- name: remove old repository
  shell: "[ $(ls -d /opt/larkin/releases/* | wc -l) -gt 3 ] && ls -d /opt/larkin/releases/* | head -1 | xargs rm -rf; true"
- name: get source code
  git:
    repo: https://github.com/getlarkin/larkin.git
    dest: /opt/larkin/releases/{{ ansible_date_time.iso8601_basic }}
    depth: 1
    accept_hostkey: True
- name: copy env file
  copy:
    src: .env
    dest: /opt/larkin/releases/{{ ansible_date_time.iso8601_basic }}/{{ item }}
  with_items:
    - .env
    - packages/api/.env
- name: commands
  command: "{{ item }}"
  args:
    chdir: /opt/larkin/releases/{{ ansible_date_time.iso8601_basic }}
  with_items:
    - yarn install
    - yarn db:migrate
    # - yarn db:seed
- name: link
  file:
    src: /opt/larkin/releases/{{ ansible_date_time.iso8601_basic }}
    dest: /opt/larkin/current
    state: link
