- name: insecure repo
  become: True
  copy:
    src: docker-daemon.json
    dest: /etc/docker/daemon.json
    mode: 0755
- name: add to service
  become: True
  copy:
    src: larkin-api.service
    dest: /etc/systemd/system/larkin-api.service
    mode: 0755
